function grafica3d(X1, Y1, Z1,tit)
%CREATEFIGURE(X1, Y1, Z1)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Z1:  vector of z data

%  Auto-generated by MATLAB on 21-Feb-2020 18:38:56

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot3
plot3(X1,Y1,Z1);

% Create xlabel
xlabel('x');
ylabel('y');
zlabel('z');

% Create title
title({tit});

view(axes1,[-37.5 30]);
grid(axes1,'on');