function grafica2d(X1, Y1,tit)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 18-Feb-2020 19:52:49

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1);

% Create ylabel
ylabel('y');

% Create xlabel
xlabel('t');

% Create title
title(tit);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-2 3]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-5 30]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XAxisLocation','origin','XGrid','on','YAxisLocation','origin',...
    'YGrid','on');